services:
  postgres:
    image: 'postgis/postgis:15-3.4'
    restart: always
    volumes:
      - './entrypoint-scripts:/docker-entrypoint-initdb.d'
    environment:
      - POSTGRES_PASSWORD=4WT0_TEST#!!
    ports:
      - '5432:5432'